# Generated by Django 4.1.2 on 2022-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('account_number', models.IntegerField(default=0)),
            ],
        ),
    ]
