# Generated by Django 4.1.2 on 2022-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributed_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
